#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

# Update translation catalogs (.po files) with new messages from the .pot template
# This script uses pybabel to merge new messages into existing .po files
# or create new .po files for new locales.
#
# Usage:
#   ./scripts/i18n/update_catalogs.sh
#
# Requirements:
#   - pybabel (from babel package)
#   - Python 3.10+
#   - vllm.pot file (generated by extract_messages.sh)

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCALES_DIR="$PROJECT_ROOT/vllm/i18n/locales"
POT_FILE="$LOCALES_DIR/vllm.pot"

echo "vLLM Catalog Update Tool"
echo "========================"
echo "Project root: $PROJECT_ROOT"
echo "Locales directory: $LOCALES_DIR"
echo "Template file: $POT_FILE"
echo ""

# Check if pybabel is available
if ! command -v pybabel &> /dev/null; then
    echo "ERROR: pybabel not found. Please install it with:"
    echo "  pip install babel"
    exit 1
fi

# Check if the .pot file exists
if [ ! -f "$POT_FILE" ]; then
    echo "ERROR: Template file not found: $POT_FILE"
    echo "Please run extract_messages.sh first"
    exit 1
fi

# List of supported locales
LOCALES=("en" "zh_CN" "de" "fr" "ja")

echo "Updating translation catalogs..."
echo ""

for locale in "${LOCALES[@]}"; do
    locale_dir="$LOCALES_DIR/$locale/LC_MESSAGES"
    po_file="$locale_dir/vllm.po"
    
    # Create locale directory if it doesn't exist
    mkdir -p "$locale_dir"
    
    if [ -f "$po_file" ]; then
        # Update existing .po file
        echo "Updating: $locale/LC_MESSAGES/vllm.po"
        pybabel update \
            -i "$POT_FILE" \
            -d "$LOCALES_DIR" \
            -l "$locale" \
            -D vllm \
            --no-fuzzy-matching
        echo "  ✓ Updated"
    else
        # Create new .po file for this locale
        echo "Creating: $locale/LC_MESSAGES/vllm.po"
        pybabel init \
            -i "$POT_FILE" \
            -d "$LOCALES_DIR" \
            -l "$locale" \
            -D vllm
        echo "  ✓ Created"
    fi
done

echo ""
echo "✓ Successfully updated all translation catalogs"
echo ""
echo "Next steps:"
echo "  1. Edit the .po files to add translations"
echo "  2. Run compile_catalogs.sh to compile .po files to .mo files"
echo ""
echo "Catalog files:"
for locale in "${LOCALES[@]}"; do
    echo "  - $LOCALES_DIR/$locale/LC_MESSAGES/vllm.po"
done
